//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace eg.skrift.data.Models
{
	// Mixin content Type 1144 with alias "eventBase"
	/// <summary>Event Base</summary>
	public partial interface IEventBase : IPublishedContent
	{
		/// <summary>Event Summary</summary>
		string EventSummary { get; }

		/// <summary>Event Title</summary>
		string EventTitle { get; }
	}

	/// <summary>Event Base</summary>
	[PublishedContentModel("eventBase")]
	public partial class EventBase : PublishedContentModel, IEventBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "eventBase";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public EventBase(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EventBase, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Event Summary: Summary of the Event
		///</summary>
		[ImplementPropertyType("eventSummary")]
		public string EventSummary
		{
			get { return GetEventSummary(this); }
		}

		/// <summary>Static getter for Event Summary</summary>
		public static string GetEventSummary(IEventBase that) { return that.GetPropertyValue<string>("eventSummary"); }

		///<summary>
		/// Event Title: Title of the Event
		///</summary>
		[ImplementPropertyType("eventTitle")]
		public string EventTitle
		{
			get { return GetEventTitle(this); }
		}

		/// <summary>Static getter for Event Title</summary>
		public static string GetEventTitle(IEventBase that) { return that.GetPropertyValue<string>("eventTitle"); }
	}
}
