//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace eg.skrift.data
{
	/// <summary>Prerecorded Event</summary>
	[PublishedContentModel("prerecordedEvent")]
	public partial class PrerecordedEvent: IEventBase
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "prerecordedEvent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PrerecordedEvent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PrerecordedEvent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Event Summary: Summary of the Event
		///</summary>
		[ImplementPropertyType("eventSummary")]
		public string EventSummary
		{
			get { return eg.skrift.data.EventBase.GetEventSummary(this); }
		}

		///<summary>
		/// Event Title: Title of the Event
		///</summary>
		[ImplementPropertyType("eventTitle")]
		public string EventTitle
		{
			get { return eg.skrift.data.EventBase.GetEventTitle(this); }
		}
	}
}
